name: "question"
description: "有些问题需要去解决。"
body:
  - type: textarea
    id: question-description
    attributes:
      label: 问题描述
      description: 提出你的问题点，包括你对问题的思考，而不要一句话直接问为什么。
      value: |
        1. 我做了什么...
        2. 希望实现什么 ...
        3. 但是实际上是什么 ...
        4. 我认为问题可能出现在哪里...
      render: bash
    validations:
      required: true
 - type: textarea
    id: err-screenshot
    attributes:
      label: 问题或报错截图
      description: 如果有报错，包括浏览器报错，脚手架报错，IDE 报错，请提供报错的完整截图。
